version: "3.8"

services:
  postgres:
    container_name: bookstore_db
    image: postgres:14.7-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-db:/data/postgres

volumes:
  postgres-db:
    driver: local
